---
title: "Draft R Markdown document"
author:
    - name: Malene Revsbech Christiansen
      affiliations:
        - name: CBMR KU
format: html
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- targets::tar_read(lipidomics)
```

## Results

```{r}
targets::tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive Statistics of the metabolites")
```

#Building the model

```{r}
#Split, map, combine!
model_estimates <- lipidomics %>%
    split_by_metabolite() %>% 
    purrr::map(generate_model_results) %>% 
    purrr::list_rbind() %>% 
    filter(stringr::str_detect(term, "metabolite_"))
#PS modellen er class, t1d. 

```

```{r}
#Just to get the normal lipid names 
lipidomics %>% 
    select(metabolite) %>% 
    mutate(term = metabolite) %>% 
    column_values_to_snake_case(term) %>% 
    mutate(term = str_c("metabolite_", term)) %>% 
    distinct(term, metabolite) %>% 
    right_join(model_estimates, by = "term")
```

## Results

### Figure of model estimates

```{r}
model_estimates <- tar_read(df_model_estimates)

#Both these will call the plot, and it can be rednered with both 
#plot_estimates(model_estimates)
tar_read(fig_model_estimates)
```
